# Nom de l'exécutable
EXECUTABLE = HoeScape

# Liste des fichiers source
SOURCES = main.c setup_game.c spawn.c game.c fonction.c threads.c

# Répertoire contenant les en-têtes
INCLUDE_DIR = Headers

# Flags de compilation
CFLAGS = -I$(INCLUDE_DIR) -lncurses

# Commande de compilation
CC = cc

# Règle par défaut pour construire l'exécutable
al$@ $^ $(CFLAGS)

# Nettoyer les fichiers générés
clean:
	rm -f $(EXECUTABLE)

